name: Create and push rockspec for migrate

on:
  workflow_run:
    workflows:
      - "Linting with luacheck"
    branches: master
    types:
      - completed
  push:
    tags:
      - '*'

env:
  ROCK_NAME: migrate

jobs:
  pack-and-push-tagged-rockspec:
   runs-on: ubuntu-latest
   if: startsWith(github.ref, 'refs/tags')
   steps:
    - uses: actions/checkout@master
    - uses: tarantool/setup-tarantool@v1
      with:
        tarantool-version: '2.6'

    # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
    - name: Set env
      run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - run: tarantoolctl rocks new_version --tag ${{ env.TAG }}
    - run: tarantoolctl rocks install ${{ env.ROCK_NAME }}-${{ env.TAG }}-1.rockspec
    - run: tarantoolctl rocks pack ${{ env.ROCK_NAME }}-${{ env.TAG }}-1.rockspec
